from __future__ import annotations
from python.benchmarks import comparison_ivar_obstacle_1teams, comparison_ivar_obstacle_3teams, comparison_ivar_maze_1teams,comparison_ivar_maze_3teams
comparison_ivar_obstacle_1teams.main()
comparison_ivar_obstacle_3teams.main()
comparison_ivar_maze_1teams.main()
comparison_ivar_maze_3teams.main()
